import Nav from '@/components/Nav'
import DashboardMenu from '@/components/DashboardMenu'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
    return (
        <section className='dashboard-wrapper'>
            <DashboardMenu />
            <div className='dashboard-view'>
                <Nav />
                {children}
            </div>
        </section>
    )
  }